steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'  
    args: 
    - '-c'
    - | 
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"

# Install dependencies and Docker Build
  - id : 'Build container image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      cp config/${BRANCH_NAME}/* ${_PATH_GDF}/package/config/
      sed -i 's/env_name/${_ENV_NAME}/g' ${_PATH_GDF}/package/config/*.json
      sed -i 's/env_prj/${_ENV_PRJ}/g' ${_PATH_GDF}/package/config/*.json
      
      cd ${_PATH_GDF}/ && \
      docker build '--tag=gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${_IMAGE_TAG}' .
    #  docker build '--tag=us-east4-docker.pkg.dev/${PROJECT_ID}/gcf-artifacts/${_IMAGE_NAME}:${_IMAGE_TAG}' .

# Push docker image
  - id: "Push the container image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${_IMAGE_TAG}"]
    # args: ["push", "us-east4-docker.pkg.dev/${PROJECT_ID}/gcf-artifacts/${_IMAGE_NAME}:${_IMAGE_TAG}"]

# Build Dataflow Flex-Template
  - id : 'build flex-template'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
    - dataflow
    - flex-template
    - build
    - gs://${_ARTIFACTS_BUCKET_NAME}/dataflow/templates/${_IMAGE_NAME}.json
    - --image=gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${_IMAGE_TAG}
    # - --image=us-east4-docker.pkg.dev/${PROJECT_ID}/gcf-artifacts/${_IMAGE_NAME}:${_IMAGE_TAG}
    - --service-account-email="${_SA_EMAIL}"
    - --sdk-language=PYTHON


images:
  - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${_IMAGE_TAG}'
  # - 'us-east4-docker.pkg.dev/${PROJECT_ID}/gcf-artifacts/${_IMAGE_NAME}:${_IMAGE_TAG}'

options:
  logging: CLOUD_LOGGING_ONLY

tags: ['cloud-builders-community']